services:
  notesgen:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: notesgen_backend
    volumes:
      - "/home/combatrickshaw/logs/:/var/log/notesgen/"
    ports:
      - "3000:3000"
    networks:
      - dockyard

  prometheus:
    image: prom/prometheus
    container_name: notesgen_prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - dockyard
    depends_on:
      - notesgen

  grafana:
    image: grafana/grafana-oss
    container_name: notesgen_grafana
    ports:
      - "3100:3000"
    networks:
      - dockyard
    depends_on:
      - prometheus

  loki:
    image: grafana/loki
    container_name: notesgen_loki
    ports:
      - "3200:3100"
    volumes:
      - "./loki-config.yml:/mnt/config/loki-config.yaml"
    networks:
      - dockyard

  promtail:
    image: grafana/promtail
    container_name: notesgen_promtail
    volumes:
      - "./promtail-config.yml:/mnt/config/promtail-config.yaml"
      - "/home/combatrickshaw/logs/:/var/log/"
    networks:
      - dockyard
    depends_on:
      - loki

networks:
  dockyard:
    driver: bridge
